### ISSUE TITLE
Receiving an error on validating any number on ios

### ISSUE THREAD

**Issue by amirsaidgng** [flutter-form-builder-ecosystem/phone_number#100]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package/Plugin version

1.0.0

### Flutter doctor

<details>
  <summary>Flutter doctor</summary>

```bash

```

</details>

### Minimal code example

<details>
  <summary>Code sample</summary>

```dart

```

</details>

### Current Behavior

.

### Expected Behavior

.

### Steps To Reproduce

.

### Aditional information

[Client] Updating selectors after delegate addition failed with: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service with pid 95 named com.apple.commcenter.coretelephony.xpc was invalidated from this process." UserInfo={NSDebugDescription=The connection to service with pid 95 named com.apple.commcenter.coretelephony.xpc was invalidated from this process.}

**Comment by deandreamatias** [comment]
Hi, if don't fill all field on this issue, I will close it
Thanks

**Comment by amirsaidgng** [comment]
Updated.

**Comment by deandreamatias** [comment]
Please, [get package directly from repository](https://dart.dev/tools/pub/dependencies#git-packages) and try again.
The last changes isn't on pub.dev yet

**Comment by amirsaidgng** [comment]
Compilation is failing. The error is given below:

`Launching lib/main.dart on Amir Said’s iPhone in debug mode...
Signing iOS app for device deployment using developer identity: "Apple Development: amir.s@gnginfotech.com (6L34444L6F)"
CocoaPods' output:
↳
      Preparing
    Analyzing dependencies
    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)
    Finding Podfile changes
      - Flutter
      - camera_avfoundation
      - file_picker
      - flutter_image_compress
      - flutter_native_splash
      - flutter_secure_storage
      - google_maps_flutter_ios
      - google_sign_in_ios
      - image_editor_common
      - libphonenumber_plugin
      - location
      - path_provider_foundation
      - permission_handler_apple
      - phone_number
      - sign_in_with_apple
      - video_player_avfoundation
    Fetching external sources
    -> Fetching podspec for `Flutter` from `Flutter`
    -> Fetching podspec for `camera_avfoundation` from `.symlinks/plugins/camera_avfoundation/ios`
    -> Fetching podspec for `file_picker` from `.symlinks/plugins/file_picker/ios`
    -> Fetching podspec for `flutter_image_compress` from `.symlinks/plugins/flutter_image_compress/ios`
    -> Fetching podspec for `flutter_native_splash` from `.symlinks/plugins/flutter_native_splash/ios`
    -> Fetching podspec for `flutter_secure_storage` from `.symlinks/plugins/flutter_secure_storage/ios`
    -> Fetching podspec for `google_maps_flutter_ios` from `.symlinks/plugins/google_maps_flutter_ios/ios`
    -> Fetching podspec for `google_sign_in_ios` from `.symlinks/plugins/google_sign_in_ios/ios`
    -> Fetching podspec for `image_editor_common` from `.symlinks/plugins/image_editor_common/ios`
    -> Fetching podspec for `libphonenumber_plugin` from `.symlinks/plugins/libphonenumber_plugin/ios`
    -> Fetching podspec for `location` from `.symlinks/plugins/location/ios`
    -> Fetching podspec for `path_provider_foundation` from `.symlinks/plugins/path_provider_foundation/ios`
    -> Fetching podspec for `permission_handler_apple` from `.symlinks/plugins/permission_handler_apple/ios`
    -> Fetching podspec for `phone_number` from `.symlinks/plugins/phone_number/ios`
    -> Fetching podspec for `sign_in_with_apple` from `.symlinks/plugins/sign_in_with_apple/ios`
    -> Fetching podspec for `video_player_avfoundation` from `.symlinks/plugins/video_player_avfoundation/ios`
    Resolving dependencies of `Podfile`
      CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: all_pods_versions_1_6_1.txt exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/1/6/1/DKImagePickerController/4.3.4/DKImagePickerController.podspec.json exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/1/6/1/DKImagePickerController/4.3.4/DKImagePickerController.podspec.json exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: all_pods_versions_5_d_c.txt exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/5/d/c/Mantle/2.2.0/Mantle.podspec.json exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: all_pods_versions_1_1_7.txt exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/1/1/7/SDWebImage/5.15.6/SDWebImage.podspec.json exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: all_pods_versions_e_9_d.txt exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/e/9/d/SDWebImageWebPCoder/0.11.0/SDWebImageWebPCoder.podspec.json exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: all_pods_versions_a_d_d.txt exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/a/d/d/GoogleMaps/7.4.0/GoogleMaps.podspec.json exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: all_pods_versions_d_4_0.txt exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/d/4/0/GoogleSignIn/7.0.0/GoogleSignIn.podspec.json exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: all_pods_versions_2_4_b.txt exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/2/4/b/PhoneNumberKit/3.3.4/PhoneNumberKit.podspec.json exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: all_pods_versions_4_2_c.txt exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/4/2/c/FlutterMacOS/3.0.0/FlutterMacOS.podspec.json exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/2/4/b/PhoneNumberKit/3.3.4/PhoneNumberKit.podspec.json exists! Returning local because checking is only performed in repo update
    [!] CocoaPods could not find compatible versions for pod "PhoneNumberKit/PhoneNumberKitCore":
      In snapshot (Podfile.lock):
        PhoneNumberKit/PhoneNumberKitCore (= 3.3.4)
      In Podfile:
        phone_number (from `.symlinks/plugins/phone_number/ios`) was resolved to 1.0.0, which depends on
          PhoneNumberKit/PhoneNumberKitCore (= 3.5.8)
    Specs satisfying the `PhoneNumberKit/PhoneNumberKitCore (= 3.3.4), PhoneNumberKit/PhoneNumberKitCore (= 3.5.8)` dependency were found, but they required a higher minimum deployment target.
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:317:in `raise_error_unless_state'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:299:in `block in unwind_for_conflict'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:297:in `tap'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:297:in `unwind_for_conflict'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:257:in `process_topmost_state'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:182:in `resolve'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolver.rb:43:in `resolve'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.1/lib/cocoapods/resolver.rb:94:in `resolve'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.1/lib/cocoapods/installer/analyzer.rb:1082:in `block in resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.1/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.1/lib/cocoapods/installer/analyzer.rb:1080:in `resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.1/lib/cocoapods/installer/analyzer.rb:125:in `analyze'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.1/lib/cocoapods/installer.rb:422:in `analyze'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.1/lib/cocoapods/installer.rb:244:in `block in resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.1/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.1/lib/cocoapods/installer.rb:243:in `resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.1/lib/cocoapods/installer.rb:162:in `install!'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.1/lib/cocoapods/command/install.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.1/lib/cocoapods/command.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.1/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:23:in `load'
    /usr/local/bin/pod:23:in `<main>'
Error output from CocoaPods:
↳
    [!] Automatically assigning platform `iOS` with version `11.0` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.
Exception: Error running pod install
Exited
`

**Comment by amirsaidgng** [comment]
Working fine now. Thank you.

Just in case anyone stumbles upon this issue,

use this link if you get pod repo out of date

https://stackoverflow.com/questions/64443888/flutter-cocoapodss-specs-repository-is-too-out-of-date-to-satisfy-dependencies

**Comment by fabienbranchel** [comment]
Doesn't works for me. Trying with : 

```
  phone_number:
    git:
      url: https://github.com/flutter-form-builder-ecosystem/phone_number.git
      ref: 1.0.0
```

Same issue. Am I missing something ? 

 I can't try the 2.0.0 version because my project is currently working with Dart 2.

**Comment by deandreamatias** [comment]
This only work with 2.0 version
